### ISSUE TITLE
Calling right after Navigator.pop returns Null check operator used on a null value

### ISSUE THREAD

**Issue by bmercan** [abdulmanafpfassal/mtoast#2]
I was trying to inform my user after closing bottom modal sheet with mtoast but when bottom modal sheet and toast shows on returns Null check operator used on a null value.

**Comment by abdulmanafpfassal** [comment]
> I was trying to inform my user after closing bottom modal sheet with mtoast but when bottom modal sheet and toast shows on returns Null check operator used on a null value.

Can you please attach a demo video?

**Comment by abdulmanafpfassal** [comment]
Please attach a video demo

**Comment by abdulmanafpfassal** [comment]
> I was trying to inform my user after closing bottom modal sheet with mtoast but when bottom modal sheet and toast shows on returns Null check operator used on a null value.


Please attach a video demo
